apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: student-replicaset
  labels:
    app: student-app
spec:
  replicas: 3  # Number of Pod replicas
  selector:
    matchLabels:
      app: student-app
  template:
    metadata:
      labels:
        app: student-app
    spec:
      containers:
        - name: student-container
          image: student-app:latest  # Your Docker Hub image
          ports:
            - containerPort: 8080